### ISSUE TITLE
Issue while building

### ISSUE THREAD

**Issue by marco-04** [Universal-Team/ForwarDS#1]
Hi, I wanted to build ForwarDS, as there are no prebuilt binaries, and I wanted to try this homebrew app. I've installed DevkitPro and I cloned the repo with the Universal Core submodule. Then I started the "compile.bat" file, but I got a bunch of errors and it stopped.

![image](https://user-images.githubusercontent.com/61947904/148226313-ff2b9718-bafe-4de0-8732-ce5c0295bbc8.png)

I don't know how to proceed in this case. Are there any other things I'm missing? Also, does the app actually work when compiled? Because the fact that there's no binary gives me the doubt that it's not going to work properly even if I overcome these problems

**Comment by Epicpkmn11** [comment]
Looks like the gfx folders were missing due to being empty, should be fixed with the new commit
